"""
C4 / Structurizr DSL export.

Maps the module-level rollup of the call graph to a C4 component diagram in
Structurizr DSL — the enterprise-architect Trojan horse: their existing tooling
(Structurizr, PlantUML via the C4 extension) ingests our deterministic ground
truth instead of a hand-drawn approximation.
"""

from __future__ import annotations

import re
from typing import Dict, List

import networkx as nx

from pyvisualizer.visualizers.mermaid import _rollup


def _ident(key: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9_]", "_", key)
    if not ident or not ident[0].isalpha():
        ident = "c_" + ident
    return ident


def generate_c4_dsl(G: nx.DiGraph, project_name: str = "System") -> str:
    """Generate a Structurizr DSL workspace from the module-level graph."""
    groups, edges = _rollup(G, "module")

    name = project_name or "System"
    lines: List[str] = []
    lines.append(f'workspace "{name}" "Auto-generated by py-code-visualizer" {{')
    lines.append("    model {")
    lines.append(f'        system = softwareSystem "{name}" {{')

    ids: Dict[str, str] = {}
    for key in sorted(groups):
        ident = _ident(key)
        # Guard against collisions after sanitization.
        base = ident
        i = 1
        while ident in ids.values():
            ident = f"{base}_{i}"
            i += 1
        ids[key] = ident
        label = groups[key]["label"].replace('"', "'")
        lines.append(f'            {ident} = component "{label}" "{key}"')

    for sk, tk in sorted(edges):
        lines.append(f'            {ids[sk]} -> {ids[tk]} "calls"')

    lines.append("        }")
    lines.append("    }")
    lines.append("    views {")
    lines.append("        component system {")
    lines.append("            include *")
    lines.append("            autoLayout lr")
    lines.append("        }")
    lines.append("        theme default")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)
