"""
AI-oriented export.

Emits a verified, compact architecture summary for LLM/agent consumption
(Cursor, Claude, etc.) so tools ingest deterministic ground truth instead of
re-deriving the architecture — wrongly — from raw source. The pattern: *point
your agent at the graph, not the repo.*
"""

from __future__ import annotations

import json
import os
from typing import Dict, List

import networkx as nx

from pyvisualizer.api import GraphResult
from pyvisualizer.gates import find_cycles
from pyvisualizer.metrics import compute_health, find_dead_code
from pyvisualizer.serializers.json_graph import graph_to_dict


def _entry_points(G: nx.DiGraph) -> List[str]:
    from pyvisualizer.metrics import _is_entry_point

    eps = [n for n in G.nodes() if _is_entry_point(n, G.nodes[n]) and G.out_degree(n) > 0]
    eps.sort(key=lambda n: G.out_degree(n), reverse=True)
    return eps


def build_ai_markdown(result: GraphResult, tool_version: str = "") -> str:
    """Build a compact, llms.txt-style architecture summary."""
    G = result.graph
    health = compute_health(G)
    cycles = find_cycles(G)
    dead = find_dead_code(G)
    eps = _entry_points(G)

    modules: Dict[str, int] = {}
    for n in G.nodes():
        m = G.nodes[n].get("module", "")
        modules[m] = modules.get(m, 0) + 1

    lines: List[str] = []
    lines.append(f"# Architecture — {result.project_name}")
    lines.append("")
    lines.append(
        "> Deterministic, AST-verified call graph. Every relationship "
        "below is traceable to a line of code — no inference, no guessing. "
        "Use this as ground truth instead of re-reading the raw repository."
    )
    lines.append("")
    lines.append(f"- Functions: **{G.number_of_nodes()}**")
    lines.append(f"- Call edges: **{G.number_of_edges()}**")
    lines.append(f"- Health: **{health.grade}** ({health.score}/100)")
    lines.append(f"- Circular dependencies: **{len(cycles)}**")
    lines.append(f"- Generated by py-code-visualizer {tool_version}".rstrip())
    lines.append("")

    lines.append("## Modules")
    lines.append("")
    for m in sorted(modules):
        lines.append(f"- `{m}` — {modules[m]} definition(s)")
    lines.append("")

    if eps:
        lines.append("## Entry points")
        lines.append("")
        for ep in eps[:15]:
            lines.append(f"- `{ep}`")
        lines.append("")

    if cycles:
        lines.append("## Circular dependencies (fix these first)")
        lines.append("")
        for c in cycles[:15]:
            chain = " → ".join(x.split(".")[-1] for x in c) + " → " + c[0].split(".")[-1]
            lines.append(f"- `{chain}`")
        lines.append("")

    if health.god_nodes:
        lines.append("## High-risk hubs (high fan-in/out)")
        lines.append("")
        for g in health.god_nodes[:15]:
            lines.append(f"- `{g}`")
        lines.append("")

    if dead:
        lines.append("## Possibly unused (no in-project callers)")
        lines.append("")
        for d in dead[:20]:
            lines.append(f"- `{d}`")
        lines.append("")

    lines.append("## How to use this file")
    lines.append("")
    lines.append(
        "Load `ARCHITECTURE.json` for the full machine-readable graph "
        "(nodes with file:line, edges with confidence). Ask questions "
        'against it — "who calls X", "what breaks if I change Y" — '
        "rather than asking a model to reconstruct structure from source."
    )
    return "\n".join(lines)


def export_for_ai(
    result: GraphResult,
    out_dir: str = ".",
    tool_version: str = "",
) -> Dict[str, str]:
    """Write ARCHITECTURE.json and ARCHITECTURE.md; return the paths written."""
    os.makedirs(out_dir, exist_ok=True)
    json_path = os.path.join(out_dir, "ARCHITECTURE.json")
    md_path = os.path.join(out_dir, "ARCHITECTURE.md")

    data = graph_to_dict(
        result.graph,
        project_name=result.project_name,
        project_root=result.project_root,
        tool_version=tool_version,
    )
    data["health"] = compute_health(result.graph).to_dict()
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(build_ai_markdown(result, tool_version))

    return {"json": json_path, "markdown": md_path}
