"""
Self-healing documentation injection.

Injects (or updates) an auto-generated Mermaid diagram inside a Markdown file
between sentinel markers. Idempotent: if the graph has not changed, the file is
left byte-identical, so the CI bot never produces a phantom commit.

    <!-- pyvisualizer:start -->
    ```mermaid
    ...diagram...
    ```
    <!-- pyvisualizer:end -->
"""

from __future__ import annotations

import os
from typing import Optional, Tuple

START_MARKER = "<!-- pyvisualizer:start -->"
END_MARKER = "<!-- pyvisualizer:end -->"
_AUTOGEN_NOTE = (
    "<!-- This diagram is auto-generated by py-code-visualizer. "
    "Do not edit by hand; run `py-code-visualizer readme` to refresh. -->"
)
_FENCE = "```"


def build_block(
    mermaid_code: str,
    *,
    heading: Optional[str] = None,
    footer: Optional[str] = None,
) -> str:
    """Build the full marker-delimited block for a Mermaid diagram."""
    lines = [START_MARKER, _AUTOGEN_NOTE]
    if heading:
        lines.append("")
        lines.append(heading)
    lines.append("")
    lines.append(f"{_FENCE}mermaid")
    lines.append(mermaid_code.rstrip("\n"))
    lines.append(_FENCE)
    if footer:
        lines.append("")
        lines.append(footer)
    lines.append(END_MARKER)
    return "\n".join(lines)


def inject_block(
    content: str,
    block: str,
    *,
    start_marker: str = START_MARKER,
    end_marker: str = END_MARKER,
    section_title: str = "## 🗺️ Architecture",
) -> Tuple[str, bool]:
    """Return ``(new_content, changed)`` after injecting/updating a marker block.

    Generic over the marker pair and the block content, so both the Mermaid
    diagram (readme) and other sections (e.g. AGENTS.md) share one idempotent
    replace-between-markers-or-append implementation.
    """
    start = content.find(start_marker)
    end = content.find(end_marker)

    if start != -1 and end != -1 and end > start:
        end_full = end + len(end_marker)
        new_content = content[:start] + block + content[end_full:]
        return new_content, (new_content != content)

    # Markers absent -> append a new section.
    separator = (
        ""
        if content.endswith("\n\n") or content == ""
        else ("\n" if content.endswith("\n") else "\n\n")
    )
    addition = f"{separator}{section_title}\n\n{block}\n"
    new_content = content + addition
    return new_content, True


def inject(
    content: str,
    mermaid_code: str,
    *,
    heading: Optional[str] = None,
    footer: Optional[str] = None,
    section_title: str = "## 🗺️ Architecture",
) -> Tuple[str, bool]:
    """Return ``(new_content, changed)`` after injecting/updating the diagram block.

    - If both markers are present, replace whatever is between them.
    - If markers are absent, append a new titled section at the end.
    - ``changed`` is False when the file already contains the exact block.
    """
    block = build_block(mermaid_code, heading=heading, footer=footer)
    return inject_block(content, block, section_title=section_title)


def update_file(
    target_path: str,
    mermaid_code: str,
    *,
    heading: Optional[str] = None,
    footer: Optional[str] = None,
    section_title: str = "## 🗺️ Architecture",
) -> bool:
    """Inject/update the diagram in ``target_path``.

    Returns True if the file was modified (created or changed), False if it was
    already up to date. Creates the file if it does not exist.
    """
    if os.path.exists(target_path):
        with open(target_path, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = ""

    new_content, changed = inject(
        content,
        mermaid_code,
        heading=heading,
        footer=footer,
        section_title=section_title,
    )
    if changed:
        with open(target_path, "w", encoding="utf-8") as f:
            f.write(new_content)
    return changed
